default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: todomap_development

production:
  <<: *default
  database: todomap_test
  username: sample_app
  password: password
